# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'seebi/tmux-colors-solarized'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Tmuxline config
# Documentation instructions and packaged conf file do not work, but straight
# shell calls of the powerline-config does get this working correctly. Vim is
# using python3 for powerline while tmux uses 2.7
# run-shell "powerline-daemon -q"
# run-shell "powerline-config tmux setup"

# Solarized theme and term configs
set -g @colors-solarized 'light'
# set -g @colors-solarized 'dark'
set -g default-terminal 'tmux-256color'
set -as terminal-overrides ',xterm*:Tc:sitm=\E[3m'
# set -ga terminal-overrides ",xterm-256color*:Tc"

# Misc
set -g base-index 1

# key bindings
set-option -g prefix C-a
unbind-key C-a
bind-key C-a send-prefix

set -g base-index 1				# 0 is silly default index
setw -g mode-keys vi
# setw -g mouse on

bind -n M-d detach-client
bind -n M-c new-window
bind -n M-| split-window -h
bind -n M-- split-window -v
bind x kill-pane
bind X kill-window

bind -n M-1 select-window -t :1
bind -n M-2 select-window -t :2
bind -n M-3 select-window -t :3
bind -n M-4 select-window -t :4
bind -n M-5 select-window -t :5
bind -n M-6 select-window -t :6
bind -n M-7 select-window -t :7
bind -n M-8 select-window -t :8
bind -n M-9 select-window -t :9

bind-key t next-window
bind-key T previous-window
bind-key k select-pane -U
bind-key j select-pane -D
bind-key h select-pane -L
bind-key l select-pane -R

bind -n M-j resize-pane -D
bind -n M-k resize-pane -U
bind -n M-h resize-pane -L
bind -n M-l resize-pane -R

# We want to have single prefix key "C-a", usable both for local and remote
# session
# we don't want to "C-a" + "a" approach either
# Idea is to turn off all key bindings and prefix handling on local session,
# so that all keystrokes are passed to inner/remote session

# see: toggle on/off all keybindings · Issue #237 · tmux/tmux -
# https://github.com/tmux/tmux/issues/237

# Also, change some visual styles when window keys are off
bind -T root F12  \
    set prefix None \;\
    set key-table off \;\
    if -F '#{pane_in_mode}' 'send-keys -X cancel' \;\
    refresh-client -S \;\

bind -T off F12 \
  set -u prefix \;\
  set -u key-table \;\
  refresh-client -S

# Initialize TX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
