# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
HISTFILE=$HOME/.cache/zsh_history
ETC_DIR=~/etc/`hostname -f`/`id -un`/

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.

# ZSH_THEME="powerlevel9k/powerlevel9k" 				# based on simple
ZSH_THEME="spaceship" 				# based on simple
POWERLEVEL9K_MODE="nerdfont-complete"

# Customise PowerLevel9k
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_last"
POWERLEVEL9K_SHORTEN_DELIMITER=".."
POWERLEVEL9K_HOME_ICON=''
POWERLEVEL9K_HOME_SUB_ICON=''
POWERLEVEL9K_FOLDER_ICON=''
POWERLEVEL9K_ETC_ICON=''
POWERLEVEL9K_COLOR_SCHEME='light'


# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git svn osx tmux)

source $ZSH/oh-my-zsh.sh
setopt NO_AUTO_PUSHD
setopt NO_CORRECT


# Customize to your needs...
# export PATH=~/Library/Python/2.7/bin:/usr/local/bin:/usr/local/sbin:$PATH:$HOME/bin
export MANPATH=/usr/local/share/man:/usr/share/man:$MANPATH

source ~/.alias
export BAT_THEME="Solarized (dark)"
# source /usr/local/opt/chruby/share/chruby/chruby.sh
# source /usr/local/opt/chruby/share/chruby/auto.sh

# TERM='xterm-256color'

# eval `eval 'dircolors ~/.dircolors'`
# LSCOLORS=exfxfeaeBxxehehbadacea

# [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
