
ZSH=$HOME/.oh-my-zsh
HISTFILE=$HOME/.cache/zsh_history
# ETC_DIR=~/etc/`hostname -f`/`id -un`/

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.

# ZSH_THEME="powerlevel9k/powerlevel9k" 				# based on simple
ZSH_THEME="spaceship" 				# based on simple
# POWERLEVEL9K_MODE="nerdfont-complete"

source $ZSH/oh-my-zsh.sh
setopt NO_AUTO_PUSHD
setopt NO_CORRECT

plugins=(git svn osx tmux)



# Customize to your needs...
export MANPATH=/usr/local/share/man:/usr/share/man:$MANPATH
export PATH=/usr/local/bin:/usr/local/sbin:$HOME/bin:$HOME/.local/bin:$PATH

source ~/.alias
export BAT_THEME="Solarized (dark)"

# TERM='xterm-256color'

# eval `eval 'dircolors ~/.dircolors'`
# LSCOLORS=exfxfeaeBxxehehbadacea


# Keybindings for fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Setup for pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

# alacritty day/night colourscheme toggle
function reload_nvim {
    for SERVER in $(nvr --serverlist); do
        nvr -cc "source ~/.vim/init.vim" --servername $SERVER &
    done
}

COLOR_DIR="$HOME/.config/alacritty/colours"
LIGHT_COLOR='solarized_dark.yaml'
DARK_COLOR='solarized_light.yaml'

alias day="alacritty-colorscheme -C $COLOR_DIR -a $LIGHT_COLOR -V && reload_nvim"
alias night="alacritty-colorscheme -C $COLOR_DIR -a $DARK_COLOR -V && reload_nvim"
