ZSH=$HOME/.oh-my-zsh
source $ZSH/oh-my-zsh.sh
setopt NO_AUTO_PUSHD
setopt NO_CORRECT
plugins=(git svn macos tmux)

HISTFILE=$HOME/.cache/zsh_history
source ~/.alias

eval "$(zoxide init zsh)"
eval "$(pyenv init -)"
eval "$(starship init zsh)"

# Keybindings for fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden'
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
export BAT_THEME="TwoDark"
export MANPATH=/usr/local/share/man:/usr/share/man:$MANPATH

bindkey "^P" up-line-or-beginning-search
bindkey "^N" down-line-or-beginning-search

